/*
 * Copyright (C) 2024 CircleOS
 * SPDX-License-Identifier: Apache-2.0
 */
package com.circleos.server.security;

import android.security.keystore.KeyProperties;
import android.util.Base64;
import android.util.Log;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.util.List;
import java.io.ByteArrayOutputStream;
import java.security.SecureRandom;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;
import org.json.JSONObject;

/**
 * Data Acuity Network Client.
 *
 * Handles:
 *   1. Threat feed downloads — pull c2_ips.txt, c2_domains.txt, malware_hashes.txt
 *      with Ed25519 signature verification before writing to disk.
 *   2. IOC batch submission — POST anonymized IOCs from CommunityDefenseService.
 *   3. Critical threat push handling — future: WebSocket subscription.
 *
 * Phase 2: HTTP polling (no persistent connection).
 * Phase 3: WebSocket for real-time critical threat push.
 *
 * All feeds are signed by Data Acuity's Ed25519 key (embedded at compile time).
 * A feed with an invalid signature is discarded — never written to disk.
 */
public class DataAcuityClient {

    private static final String TAG = "DataAcuity";

    // Base URL — populated from build config in real build
    private static final String BASE_URL        = "https://feeds.dataacuity.circleos.co.za";
    private static final String FEED_IPS_PATH   = "/v1/feeds/c2_ips.txt";
    private static final String FEED_DOMAINS_PATH = "/v1/feeds/c2_domains.txt";
    private static final String FEED_HASHES_PATH  = "/v1/feeds/malware_hashes.txt";
    private static final String SUBMIT_PATH     = "/v1/community/iocs";
    private static final String WS_PATH         = "/v1/ws/threats";
    private static final int    WS_PORT          = 443;

    private static final String FEEDS_DIR = "/data/circle/security/feeds/";
    private static final int    TIMEOUT_MS = 30_000;

    /**
     * Ed25519 public key for Data Acuity feed signatures (DER/SubjectPublicKeyInfo, Base64).
     * Generated by Data Acuity; embedded at build time.
     * To regenerate: openssl genpkey -algorithm ed25519 | openssl pkey -pubout -outform DER | base64
     * Replace this placeholder with the real production key before shipping.
     */
    private static final String DATA_ACUITY_PUBKEY_B64 =
            "MCowBQYDK2VwAyEA4X1oPgvApdtad/1JbAXJH3yPXbR+QkEwT/50cr4mqbA=";

    /** Cached decoded public key — loaded once on first use. */
    private volatile PublicKey mCachedPublicKey;

    // ── Phase 3: WebSocket ────────────────────────────────────────────────────
    private ThreatPushListener mWsListener;
    private final AtomicBoolean mWsRunning = new AtomicBoolean(false);
    private volatile SSLSocket mWsSocket;
    private Thread mWsThread;

    /**
     * Download and verify all threat feeds.
     * Each feed is downloaded, signature verified, then atomically written to disk.
     * @return true if all feeds were updated successfully
     */
    public boolean downloadFeeds() {
        boolean ok = true;
        ok &= downloadFeed(FEED_IPS_PATH,      "c2_ips.txt");
        ok &= downloadFeed(FEED_DOMAINS_PATH,  "c2_domains.txt");
        ok &= downloadFeed(FEED_HASHES_PATH,   "malware_hashes.txt");
        return ok;
    }

    private boolean downloadFeed(String path, String filename) {
        try {
            String feedUrl  = BASE_URL + path;
            String sigUrl   = feedUrl + ".sig";

            byte[] feedData = httpGet(feedUrl);
            byte[] sigData  = httpGet(sigUrl);

            if (feedData == null || sigData == null) {
                Log.w(TAG, "Download failed: " + filename);
                return false;
            }

            if (!verifySignature(feedData, sigData)) {
                Log.e(TAG, "Signature INVALID for " + filename + " — discarding");
                return false;
            }

            // Atomic write: write to .tmp, rename
            File tmp  = new File(FEEDS_DIR + filename + ".tmp");
            File dest = new File(FEEDS_DIR + filename);
            try (FileOutputStream fos = new FileOutputStream(tmp)) {
                fos.write(feedData);
            }
            tmp.renameTo(dest);
            Log.i(TAG, "Feed updated: " + filename + " (" + feedData.length + " bytes)");
            return true;

        } catch (Exception e) {
            Log.e(TAG, "Feed download error: " + filename, e);
            return false;
        }
    }

    /**
     * Submit a batch of anonymized IOCs to Data Acuity.
     */
    public void submitIocBatch(List<CommunityDefenseService.AnonymizedIoc> batch) {
        if (batch == null || batch.isEmpty()) return;
        try {
            StringBuilder json = new StringBuilder("[");
            for (int i = 0; i < batch.size(); i++) {
                CommunityDefenseService.AnonymizedIoc ioc = batch.get(i);
                if (i > 0) json.append(",");
                json.append("{\"type\":\"").append(ioc.type.name().toLowerCase())
                    .append("\",\"value\":\"").append(escapeJson(ioc.value))
                    .append("\",\"verdict\":").append(ioc.verdict)
                    .append(",\"confidence\":").append(ioc.confidence)
                    .append("}");
            }
            json.append("]");

            httpPost(BASE_URL + SUBMIT_PATH, json.toString().getBytes(StandardCharsets.UTF_8));
            Log.i(TAG, "Submitted " + batch.size() + " IOCs");
        } catch (Exception e) {
            Log.e(TAG, "IOC submission failed", e);
        }
    }

    /* ── Signature verification ─────────────────────────────────────────── */

    /**
     * Verify Ed25519 signature on feed data using the embedded Data Acuity public key.
     *
     * The {@code .sig} file alongside each feed contains a raw 64-byte Ed25519 signature
     * over the feed's full content.  Android's Conscrypt provider supports Ed25519 via
     * {@code Signature.getInstance("Ed25519")}.
     *
     * Returns false (never throws) so a bad signature causes feed discard, not a crash.
     */
    private boolean verifySignature(byte[] data, byte[] signature) {
        try {
            PublicKey pk = loadPublicKey();
            if (pk == null) {
                Log.e(TAG, "Ed25519 public key unavailable — rejecting feed");
                return false;
            }
            Signature sig = Signature.getInstance("Ed25519");
            sig.initVerify(pk);
            sig.update(data);
            boolean valid = sig.verify(signature);
            if (!valid) Log.e(TAG, "Ed25519 signature INVALID");
            return valid;
        } catch (Exception e) {
            Log.e(TAG, "Signature verification error", e);
            return false;
        }
    }

    /**
     * Decode and cache the Data Acuity Ed25519 public key from the embedded Base64 constant.
     * Uses X.509 SubjectPublicKeyInfo DER encoding (output of {@code openssl pkey -pubout}).
     */
    private PublicKey loadPublicKey() {
        if (mCachedPublicKey != null) return mCachedPublicKey;
        try {
            byte[] der = Base64.decode(DATA_ACUITY_PUBKEY_B64, Base64.DEFAULT);
            X509EncodedKeySpec spec = new X509EncodedKeySpec(der);
            KeyFactory kf = KeyFactory.getInstance("Ed25519");
            mCachedPublicKey = kf.generatePublic(spec);
            return mCachedPublicKey;
        } catch (Exception e) {
            Log.e(TAG, "Failed to load Ed25519 public key", e);
            return null;
        }
    }

    /* ── HTTP helpers ──────────────────────────────────────────────────── */

    private byte[] httpGet(String urlStr) {
        try {
            URL url = new URL(urlStr);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setConnectTimeout(TIMEOUT_MS);
            conn.setReadTimeout(TIMEOUT_MS);
            conn.setRequestMethod("GET");
            conn.setRequestProperty("User-Agent", "CircleOS-Security/1.0");

            int status = conn.getResponseCode();
            if (status != 200) {
                Log.w(TAG, "GET " + urlStr + " → HTTP " + status);
                return null;
            }

            try (InputStream is = conn.getInputStream()) {
                return is.readAllBytes();
            }
        } catch (Exception e) {
            Log.w(TAG, "GET failed: " + urlStr + " — " + e.getMessage());
            return null;
        }
    }

    private void httpPost(String urlStr, byte[] body) throws Exception {
        URL url = new URL(urlStr);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setConnectTimeout(TIMEOUT_MS);
        conn.setReadTimeout(TIMEOUT_MS);
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setRequestProperty("User-Agent", "CircleOS-Security/1.0");
        conn.setDoOutput(true);
        try (OutputStream os = conn.getOutputStream()) {
            os.write(body);
        }
        int status = conn.getResponseCode();
        if (status < 200 || status >= 300) {
            Log.w(TAG, "POST " + urlStr + " → HTTP " + status);
        }
    }

    private String escapeJson(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    /* ── Phase 3: WebSocket real-time threat push ──────────────────────── */

    /**
     * Callback interface for real-time threat push from Data Acuity.
     * Called on the WebSocket read thread — implementations must be thread-safe.
     */
    public interface ThreatPushListener {
        void onCriticalThreat(String iocType, String value, int confidence);
        void onFeedRefreshRequired();
    }

    /** Start WebSocket. Reconnects automatically on failure with exponential backoff. */
    public void startWebSocket(ThreatPushListener listener) {
        if (!mWsRunning.compareAndSet(false, true)) {
            Log.w(TAG, "WebSocket already running");
            return;
        }
        mWsListener = listener;
        mWsThread = new Thread(this::wsLoop, "DataAcuity-WS");
        mWsThread.setDaemon(true);
        mWsThread.start();
        Log.i(TAG, "WebSocket thread started");
    }

    /** Stop the WebSocket connection. */
    public void stopWebSocket() {
        mWsRunning.set(false);
        closeWsSocket();
        if (mWsThread != null) mWsThread.interrupt();
    }

    private void wsLoop() {
        int backoffMs = 5_000;
        while (mWsRunning.get()) {
            try {
                wsConnect();
                backoffMs = 5_000;
            } catch (InterruptedException ie) {
                break;
            } catch (Exception e) {
                Log.w(TAG, "WS disconnected: " + e.getMessage()
                        + " — retry in " + (backoffMs / 1000) + "s");
                try { Thread.sleep(backoffMs); } catch (InterruptedException ie) { break; }
                backoffMs = Math.min(backoffMs * 2, 300_000);
            }
        }
        Log.i(TAG, "WebSocket thread stopped");
    }

    private void wsConnect() throws Exception {
        String host = BASE_URL.replace("https://", "").replace("http://", "");
        SSLSocketFactory sf = (SSLSocketFactory) SSLSocketFactory.getDefault();
        SSLSocket sock = (SSLSocket) sf.createSocket(host, WS_PORT);
        sock.setSoTimeout(70_000);
        mWsSocket = sock;

        String wsKey = generateWsKey();
        String req = "GET " + WS_PATH + " HTTP/1.1\r\n"
                + "Host: " + host + "\r\n"
                + "Upgrade: websocket\r\n"
                + "Connection: Upgrade\r\n"
                + "Sec-WebSocket-Key: " + wsKey + "\r\n"
                + "Sec-WebSocket-Version: 13\r\n"
                + "User-Agent: CircleOS-Security/1.0\r\n"
                + "\r\n";
        sock.getOutputStream().write(req.getBytes(StandardCharsets.US_ASCII));
        sock.getOutputStream().flush();

        String resp = readHttpHeader(sock.getInputStream());
        if (!resp.contains("101")) {
            throw new java.io.IOException("WS handshake failed: "
                    + resp.substring(0, Math.min(resp.length(), 120)));
        }
        Log.i(TAG, "WebSocket connected");
        wsReadLoop(sock);
    }

    private void wsReadLoop(SSLSocket sock) throws Exception {
        InputStream  is = sock.getInputStream();
        OutputStream os = sock.getOutputStream();
        long lastPingMs = System.currentTimeMillis();

        while (mWsRunning.get()) {
            if (System.currentTimeMillis() - lastPingMs > 30_000) {
                wsSendFrame(os, (byte) 0x09, new byte[0]);
                lastPingMs = System.currentTimeMillis();
            }

            int b0 = is.read();
            if (b0 < 0) throw new java.io.IOException("EOF on WS stream");
            int b1 = is.read();
            if (b1 < 0) throw new java.io.IOException("EOF on WS stream");

            int     opcode     = b0 & 0x0F;
            boolean masked     = (b1 & 0x80) != 0;
            long    payloadLen = b1 & 0x7F;

            if (payloadLen == 126) {
                payloadLen = ((long)(is.read() & 0xFF) << 8) | (is.read() & 0xFF);
            } else if (payloadLen == 127) {
                payloadLen = 0;
                for (int i = 0; i < 8; i++) payloadLen = (payloadLen << 8) | (is.read() & 0xFF);
            }

            byte[] maskKey = null;
            if (masked) {
                maskKey = new byte[4];
                for (int i = 0; i < 4; i++) maskKey[i] = (byte) is.read();
            }

            int safeLen = (int) Math.min(payloadLen, 1 << 20);
            byte[] payload = new byte[safeLen];
            wsReadFully(is, payload);
            if (masked && maskKey != null) {
                for (int i = 0; i < payload.length; i++) payload[i] ^= maskKey[i % 4];
            }

            switch (opcode) {
                case 0x01: handleWsMessage(new String(payload, StandardCharsets.UTF_8)); break;
                case 0x08: Log.i(TAG, "Server WS close"); return;
                case 0x09: wsSendFrame(os, (byte) 0x0A, payload); break;
                case 0x0A: lastPingMs = System.currentTimeMillis(); break;
                default:   Log.d(TAG, "WS opcode 0x" + Integer.toHexString(opcode)); break;
            }
        }
    }

    private void handleWsMessage(String json) {
        if (mWsListener == null) return;
        try {
            JSONObject obj = new JSONObject(json);
            String msgType = obj.optString("type", "");
            Log.d(TAG, "WS: " + msgType);
            if ("CRITICAL_THREAT".equals(msgType)) {
                String iocType = obj.optString("ioc_type", "UNKNOWN");
                String value   = obj.optString("value", "");
                int confidence = obj.optInt("confidence", 50);
                if (!value.isEmpty()) mWsListener.onCriticalThreat(iocType, value, confidence);
            } else if ("FEED_REFRESH".equals(msgType)) {
                mWsListener.onFeedRefreshRequired();
            }
        } catch (Exception e) {
            Log.w(TAG, "WS parse error: " + e.getMessage());
        }
    }

    private synchronized void wsSendFrame(OutputStream os, byte opcode, byte[] payload)
            throws java.io.IOException {
        byte[] mask = new byte[4];
        new SecureRandom().nextBytes(mask);
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        buf.write(0x80 | (opcode & 0x0F));
        int len = payload.length;
        if (len < 126) {
            buf.write(0x80 | len);
        } else if (len < 65536) {
            buf.write(0x80 | 126);
            buf.write((len >> 8) & 0xFF);
            buf.write(len & 0xFF);
        } else {
            buf.write(0x80 | 127);
            for (int i = 7; i >= 0; i--) buf.write((int)((len >> (i * 8)) & 0xFF));
        }
        buf.write(mask);
        for (int i = 0; i < payload.length; i++) buf.write(payload[i] ^ mask[i % 4]);
        os.write(buf.toByteArray());
        os.flush();
    }

    private String readHttpHeader(InputStream is) throws java.io.IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        int p3 = 0, p2 = 0, p1 = 0;
        for (int b; (b = is.read()) >= 0;) {
            baos.write(b);
            if (p3 == '\r' && p2 == '\n' && p1 == '\r' && b == '\n') break;
            p3 = p2; p2 = p1; p1 = b;
        }
        return new String(baos.toByteArray(), StandardCharsets.US_ASCII);
    }

    private void wsReadFully(InputStream is, byte[] buf) throws java.io.IOException {
        int off = 0;
        while (off < buf.length) {
            int n = is.read(buf, off, buf.length - off);
            if (n < 0) throw new java.io.IOException("Unexpected EOF");
            off += n;
        }
    }

    private String generateWsKey() {
        byte[] key = new byte[16];
        new SecureRandom().nextBytes(key);
        return Base64.encodeToString(key, Base64.NO_WRAP);
    }

    private void closeWsSocket() {
        SSLSocket s = mWsSocket;
        if (s != null) { try { s.close(); } catch (Exception ignored) {} }
        mWsSocket = null;
    }
}
