/*
 * Copyright (C) 2024 CircleOS
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package za.co.circleos.personality;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * A suggestion generated by the auto-switch learner based on observed
 * manual override patterns.
 *
 * Example: "You switched to Work at 09:00 on weekdays 5 times — add a
 * time trigger?"
 */
public final class LearningSuggestion implements Parcelable {

    /** Unique suggestion identifier. */
    public String     id;

    /** Human-readable description shown to the user. */
    public String     description;

    /** Pre-built TriggerRule the user can accept with one tap. */
    public TriggerRule suggestedRule;

    /**
     * Confidence score 0–100.  Higher = more consistent pattern observed.
     * Suggestions below 50 are typically not surfaced to the user.
     */
    public int        confidence;

    public LearningSuggestion() {}

    protected LearningSuggestion(Parcel in) {
        id           = in.readString();
        description  = in.readString();
        suggestedRule = in.readParcelable(TriggerRule.class.getClassLoader());
        confidence   = in.readInt();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(description);
        dest.writeParcelable(suggestedRule, flags);
        dest.writeInt(confidence);
    }

    @Override public int describeContents() { return 0; }

    public static final Creator<LearningSuggestion> CREATOR = new Creator<LearningSuggestion>() {
        @Override public LearningSuggestion createFromParcel(Parcel in) { return new LearningSuggestion(in); }
        @Override public LearningSuggestion[] newArray(int size)        { return new LearningSuggestion[size]; }
    };
}
